services:
  db:
    image: postgres:15
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./backend/scripts/initdb.sh:/docker-entrypoint-initdb.d/initdb.sh
      - ./backend/db:/db:cached
    environment:
      - POSTGRES_PASSWORD=postgres

  web:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    working_dir: /app
    environment:
      - SOLIDITY_VERSION=v0.8.0
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    command: sh ./scripts/run_web.sh
    depends_on:
      - db
      - hardhat
      - redis

  hardhat:
    build:
      context: ./hardhat
      dockerfile: Dockerfile
    command: npx hardhat node
  
  redis:
    image: redis:7.4

volumes:
  db_data: {}