services:
  db:
    image: postgres:16
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./docker/initdb.sh:/docker-entrypoint-initdb.d/initdb.sh
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_NAME=pzipper_db

  web:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    working_dir: /code
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    command: sh ./docker/run_web.sh
    depends_on:
      - db

volumes:
  db_data: {}