services:
  db:
    image: postgres:16
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./backend/docker/initdb.sh:/docker-entrypoint-initdb.d/initdb.sh
    environment:
      - POSTGRES_PASSWORD=postgres

  web:
    build:
      context: ./backend
      dockerfile: ./docker/Dockerfile
    working_dir: /app
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    command: sh ./docker/run_web.sh
    depends_on:
      - db

  # hardhat:
  #   build:
  #     context: ./hardhat
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ./hardhat:/app
  #   ports:
  #     - "8545:8545"

volumes:
  db_data: {}