services:
  db:
    image: postgres:16
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./backend/docker/initdb.sh:/docker-entrypoint-initdb.d/initdb.sh
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_NAME=pzipper_db

  web:
    build:
      context: .
      dockerfile: ./backend/docker/Dockerfile
    working_dir: /code
    volumes:
      - ./backend:/code
    ports:
      - "8000:8000"
    command: sh ./docker/run_web.sh
    depends_on:
      - db

  # hardhat:
  #   build:
  #     context: ./hardhat
  #     dockerfile: Dockerfile
  #   container_name: hardhat_node
  #   ports:
  #     - "8545:8545"
  #   networks:
  #     - app_network

volumes:
  db_data: {}