services:
  db:
    image: postgres:16
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 7432:7432
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PORT=7432
    command: sh run_web.sh
    depends_on:
      - db

volumes:
  db_data: {}