[tool.ruff]
include = ["*.py"]
exclude = ["*frontend/*"]
line-length = 120
indent-width = 4
target-version = "py313"

[tool.ruff.lint]
select = ["B", "E", "F", "W"]
ignore = []
fixable = ["ALL"]
unfixable = []
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
preview = true
docstring-code-format = false
docstring-code-line-length = "dynamic"

[tool.isort]
profile = "black"
extend_skip = [".md", ".json"]
extend_skip_glob = ["frontend/*"]
multi_line_output = 3
use_parentheses = true
force_grid_wrap = 0
line_length = 120
wrap_length = 120
ensure_newline_before_comments = true
py_version=313