# Generated by Django 5.1.6 on 2025-02-18 20:32

import backend.storage_backends
import blockchain.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SmartContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_file', models.FileField(storage=backend.storage_backends.ContractStorage, upload_to=blockchain.models.contract_upload_to)),
                ('contract_name', models.TextField(unique=True)),
                ('contract_abi', models.JSONField(default=list)),
                ('contract_bytecode', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SmartContractDeployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=42, unique=True)),
                ('transaction_hash', models.CharField(max_length=66, unique=True)),
                ('deployed_at', models.DateTimeField(auto_now_add=True)),
                ('smart_contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blockchain.smartcontract')),
            ],
            options={
                'indexes': [models.Index(fields=['smart_contract', 'deployed_at'], name='blockchain__smart_c_40b1e4_idx')],
            },
        ),
    ]
